### PR TITLE
Fix terraform channel import

### PR DESCRIPTION
**Pull request by ltickett**
I don't think I was managing to explain the issue very well, but with the help of @timofurrer this is the fix for #74 

Now when you `terraform import discord_x_channel.y z` then `server_id` is pulled into the state correctly.

### CODE REVIEW

**Comment by Lucky3028** [comment]
`terraform import` itself isn't working! I see.

**Comment by Lucky3028** [comment]
Could you rebase? @ltickett

**Comment by ltickett** [comment]
> Could you rebase? @ltickett

Done (I think). I'm a GitLab user so not overly familiar with the GitHub UI.

Thanks @Lucky3028

**Review by Lucky3028 — APPROVED** [review]

**Comment by Lucky3028** [comment]
Thanks for your contributions!

**Pull request merged**
