### PR TITLE
Discordgo rewrite

### LINKED ISSUE #91: disgord -> discordgo?
> I had never heard of discordgo before. However, since discordgo seems to be more popular than disgord, there is a way to switch to it. Thanks!

_Originally posted by @Lucky3028 in https://github.com/Lucky3028/terraform-provider-discord/issues/77#issuecomment-1453337923_

### PR DESCRIPTION
**Pull request by Cyb3r-Jak3**
Rewrite the provider to use https://github.com/bwmarrin/discordgo over https://github.com/andersfylling/disgord it is more up to date and offers more features. It should be backwards compatible, but probably worth releasing as a breaking change.

It does currently use the master branch and will need to until https://github.com/bwmarrin/discordgo/pull/1497 makes it into a release

Closes #91

### CODE REVIEW

**Comment by Lucky3028** [comment]
Thanks for your contributions! I’ll check on this weekend. @Cyb3r-Jak3

**Comment by Cyb3r-Jak3** [comment]
@Lucky3028 friendly bump on this

**Comment by Lucky3028** [comment]
I'm very sorry for the huge delay in response!!! I will confirm within two weeks. @Cyb3r-Jak3

**Comment by Cyb3r-Jak3** [comment]
I am working on account tests for this as well to help make it easier to test.

**Comment by Lucky3028** [comment]
@Cyb3r-Jak3 
Thank you very much for your patience.
I have confirmed the operation and would like to merge it.
Could you resolve conflicts?

**Review by Lucky3028 — APPROVED** [review]

**Comment by Cyb3r-Jak3** [comment]
@Lucky3028 Should be all set

**Comment by Lucky3028** [comment]
@Cyb3r-Jak3 Thanks!

**Pull request merged**
