### PR TITLE
Add discord_webhook resource

### LINKED ISSUE #21: Add Webhook

### PR DESCRIPTION
**Pull request by Mareo**
Closes #21

### CODE REVIEW

**Review by Lucky3028 — APPROVED** [review]

**Comment by Lucky3028** [comment]
@Mareo Thanks for your contributions! Could you rebase?

**Comment by Lucky3028** [comment]
thx!

**Comment by Mareo** [comment]
@Lucky3028 do you think you could release a new version of the provider to make this feature availabe?

**Comment by Lucky3028** [comment]
@Mareo maybe within 2 days(JST).

**Pull request merged**
